# **Character Level Multi Layer Perceptron Language Model**
This is inspired by [A Neural Probabilistic Language Model](https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf) paper.

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import torch.nn.functional as F

In [2]:
# load dataset
words = open('names.txt', 'r').read().splitlines()

In [3]:
# create lookup table for converting characters to indices
chars = sorted(list(set(''.join(words)))) # all unique characters in the dataset
stoi = {s:i+1 for i,s in enumerate(chars)} # string to index

# manually enumerate start and end token since they are not visible in the dataset
start_token = '<'
end_token = '>'
stoi[start_token] = 0
stoi[end_token] = len(stoi)

# total number of unique characters plus start and end token
chars_count = len(stoi)

# index to string
itos = {i:s for s,i in stoi.items()}

itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '<',
 27: '>'}

### Build dataset
Based on given list of words creates input tensor with sequence of characters  with length equal to 'context_length' and target tensor with next character in sequence.

In [4]:
def build_dataset(words, context_length=3):
    X, Y = [], []
    for w in words:
        context = [stoi[start_token]] * context_length # context window padded with start token
        for ch in w + end_token:
            ix = stoi[ch]
            X.append(context) # for given context ...
            Y.append(ix) # ... the next character is the target
            context = context[1:] + [ix] # crop and append - sliding window
    
    return torch.tensor(X), torch.tensor(Y)

In [5]:
# X (input) and Y (output/target/label) tensors
X, Y = build_dataset(words[:1])
print(f'X.shape = {X.shape}, X.dtype = {X.dtype}')
print(f'Y.shape = {Y.shape}, Y.dtype = {Y.dtype}')

print(f'For the first word in the dataset: {start_token + words[0] + end_token}')
for i in range(len(X)):
    print(f"X[{i}] = {X[i].tolist()} = {''.join([itos[j] for j in X[i].tolist()])}"
          f" ---and target char is--> Y[{i}] = {Y[i]} = {itos[Y[i].item()]}")

X.shape = torch.Size([5, 3]), X.dtype = torch.int64
Y.shape = torch.Size([5]), Y.dtype = torch.int64
For the first word in the dataset: <emma>
X[0] = [0, 0, 0] = <<< ---and target char is--> Y[0] = 5 = e
X[1] = [0, 0, 5] = <<e ---and target char is--> Y[1] = 13 = m
X[2] = [0, 5, 13] = <em ---and target char is--> Y[2] = 13 = m
X[3] = [5, 13, 13] = emm ---and target char is--> Y[3] = 1 = a
X[4] = [13, 13, 1] = mma ---and target char is--> Y[4] = 27 = >


### Create embedding lookup table

In [6]:
# Matrix of embeddings
C = torch.randn((chars_count, 2)) # 2-dimensional embeddings

# Example of embedding single character with index 15
# since our matrix of embeddings is the same size as the number of characters
# we can simply use the index of the character to get its embedding
example_embedding = C[15]
print(f'Embedding using index C[15]={example_embedding}')

# Alternative approach would be to one-hot encode the character and then multiply it by the embedding matrix
# this will give same result because encoded vector will have only one non-zero value equal to 1
# and this will simply act as a mask for the embedding matrix
example_embedding = F.one_hot(torch.tensor([15]), num_classes=chars_count).float() @ C
print(f'Embedding using one-hot encoding and matrix multiplication={example_embedding}')

# For rest of of notebook I will use index based approach because it is more efficient
# also thanks to python semantics we can easly retrieve embedding for whole sequence of characters
# by indexing with list or tensor of integers
example_embedding = C[torch.tensor([15, 20, 5])]
print(f'Embedding for sequence of three characters C[torch.tensor([15, 20, 5])]=\n{example_embedding}')


Embedding using index C[15]=tensor([0.2002, 0.5093])
Embedding using one-hot encoding and matrix multiplication=tensor([[0.2002, 0.5093]])
Embedding for sequence of three characters C[torch.tensor([15, 20, 5])]=
tensor([[ 0.2002,  0.5093],
        [ 0.1405, -0.9713],
        [ 0.9050, -0.5691]])


In [7]:
# What is even more mind blowing is that we can index using multidimensional tensor!
# in this exaple where X is 5x3 tensor, we will get 5x3x2 tensor with embeddings for each character in each sequence in third dimension
print(f'Shape of C[X].shape={C[X].shape}')
print(f'And C[X] =\n{C[X]}')
print(f'We can also access individual ebeddings for given sequence, for example C[X][0] =\n{C[X][0]}')
print(f'Or even embedding for individual character in sequence, for example C[X][0][0] =\n{C[X][0][0]}')

Shape of C[X].shape=torch.Size([5, 3, 2])
And C[X] =
tensor([[[-0.0239,  0.4176],
         [-0.0239,  0.4176],
         [-0.0239,  0.4176]],

        [[-0.0239,  0.4176],
         [-0.0239,  0.4176],
         [ 0.9050, -0.5691]],

        [[-0.0239,  0.4176],
         [ 0.9050, -0.5691],
         [ 0.1872, -0.1071]],

        [[ 0.9050, -0.5691],
         [ 0.1872, -0.1071],
         [ 0.1872, -0.1071]],

        [[ 0.1872, -0.1071],
         [ 0.1872, -0.1071],
         [-0.0662,  1.5625]]])
We can also access individual ebeddings for given sequence, for example C[X][0] =
tensor([[-0.0239,  0.4176],
        [-0.0239,  0.4176],
        [-0.0239,  0.4176]])
Or even embedding for individual character in sequence, for example C[X][0][0] =
tensor([-0.0239,  0.4176])


In [8]:
# Embeddings for imput sequences
X_embedded = C[X]

### MLP input and hidden layers

In [9]:
# Number of inputs for first layer
# context length * number of embeddings for each character
# in our case 3 * 2 = 6 which is the same as shape[1] * shape[2] of X_embedded
# and we will pass embeddings for each character in the sequence as input to the network
input_layer_size = X_embedded.shape[1] * X_embedded.shape[2]
print(f'input_layer_size={input_layer_size}')

# number of neurons in hidden layer
hidden_layer_size = 100
print(f'hidden_layer_size={hidden_layer_size}')

# W1 represents neural network weights between input and hidden layer
W1 = torch.randn((input_layer_size, hidden_layer_size))
print(f'W1.shape={W1.shape}')

# b1 represents bias for hidden layer
b1 = torch.randn(hidden_layer_size)
print(f'b1.shape={b1.shape}')

input_layer_size=6
hidden_layer_size=100
W1.shape=torch.Size([6, 100])
b1.shape=torch.Size([100])


In [10]:
# In order to perform matrix multiplication between input and weights we need to 
# transform input tensor which is 5x3x2 into 5x6 to fit into neural network

# This is how to access all embeddings for first character in each sequence
print(f'X_embedded[:, 0, :]=\n{X_embedded[:, 0, :]}\n')

# Knowing above we can concatenate all embeddings for each character in each sequence
print(f'torch.concat + tensor list=\n{torch.concat([X_embedded[:, i, :] for i in range(X_embedded.shape[1])], dim=1)}\n')

# We can also improve it by using torch.unbind which will return list of tensors and yield same result as for loop
print(f'torch.concat + torch.unbind=\n{torch.concat(torch.unbind(X_embedded, dim=1), dim=1)}\n')

X_embedded[:, 0, :]=
tensor([[-0.0239,  0.4176],
        [-0.0239,  0.4176],
        [-0.0239,  0.4176],
        [ 0.9050, -0.5691],
        [ 0.1872, -0.1071]])

torch.concat + tensor list=
tensor([[-0.0239,  0.4176, -0.0239,  0.4176, -0.0239,  0.4176],
        [-0.0239,  0.4176, -0.0239,  0.4176,  0.9050, -0.5691],
        [-0.0239,  0.4176,  0.9050, -0.5691,  0.1872, -0.1071],
        [ 0.9050, -0.5691,  0.1872, -0.1071,  0.1872, -0.1071],
        [ 0.1872, -0.1071,  0.1872, -0.1071, -0.0662,  1.5625]])

torch.concat + torch.unbind=
tensor([[-0.0239,  0.4176, -0.0239,  0.4176, -0.0239,  0.4176],
        [-0.0239,  0.4176, -0.0239,  0.4176,  0.9050, -0.5691],
        [-0.0239,  0.4176,  0.9050, -0.5691,  0.1872, -0.1071],
        [ 0.9050, -0.5691,  0.1872, -0.1071,  0.1872, -0.1071],
        [ 0.1872, -0.1071,  0.1872, -0.1071, -0.0662,  1.5625]])



In [11]:
# But it turns out there is another great function in pytorch called torch.view
# Lets have some fun with it

a = torch.arange(16) # 1D tensor with 16 elements
print(f'a.shape={a.shape}, a={a}\n')
print(f'a.view(2, 8)=\n{a.view(2, 8)}\n')
print(f'a.view(4, 4)=\n{a.view(4, 4)}\n')
print(f'a.view(2, 2, 4)=\n{a.view(2, 2, 4)}\n')

a.shape=torch.Size([16]), a=tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

a.view(2, 8)=
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])

a.view(4, 4)=
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

a.view(2, 2, 4)=
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]])



In [12]:
# Knowing above we can use torch.view to transform our 5x3x2 tensor into 5x6
# Basically we just keep first dimension and merge all other dimensions into one
# Also it looks like 6 is the only possible value for second dimension because 3*2=6
# Knowing that we can use -1 for second dimension and pytorch will figure out the rest
X_embedded_flat = X_embedded.view(-1, 6)
print(f'X_embedded_flat.shape={X_embedded_flat.shape}\n')
print(f'X_embedded_flat=\n{X_embedded_flat}\n')

X_embedded_flat.shape=torch.Size([5, 6])

X_embedded_flat=
tensor([[-0.0239,  0.4176, -0.0239,  0.4176, -0.0239,  0.4176],
        [-0.0239,  0.4176, -0.0239,  0.4176,  0.9050, -0.5691],
        [-0.0239,  0.4176,  0.9050, -0.5691,  0.1872, -0.1071],
        [ 0.9050, -0.5691,  0.1872, -0.1071,  0.1872, -0.1071],
        [ 0.1872, -0.1071,  0.1872, -0.1071, -0.0662,  1.5625]])



### First layer multiplication to get outputs from hidden layer
Our current desing of network is: 6 inputs which represents 2 dimensional embeddings for 3 character long sequence that go into 100 neurons in hidden layer and what we get is 100 outputs for each input sequence..

In [13]:
h = torch.tanh(X_embedded_flat @ W1 + b1) 
# + b1 is broadcasted to match shape of X_embedded_flat @ W1
# 5, 100
# 1, 100 - broadcasting will align on the right, create fake dimension on the left
# and will be copy b1 values 5 times to match shape of (X_embedded_flat @ W1) and perform elementwise addition
# and will result of adding 5x100 matrix to 5x100 matrix with copied values from b1
print(f'h.shape={h.shape}\n')

h.shape=torch.Size([5, 100])



### Output layer
Takes 100 outputs from hidden layer and produces output that represent one_hot_encoding for our characters set for each input sequence.

In [14]:
W2 = torch.randn((hidden_layer_size, chars_count))
b2 = torch.randn(chars_count)

In [15]:
# forwad pass for output layer
logits = h @ W2 + b2

# calculate output probabilities (the old way, manualy calculating softmax)
counts = logits.exp()
probs = counts / counts.sum(dim=1, keepdim=True)

# but there is faster way to calculate probabilities - use torch.nn.functional.softmax
# and this is equivalent to above calculation
probs = F.softmax(logits, dim=1)
probs.shape

torch.Size([5, 28])

In [16]:
# And what we see here is output character probabilities for second input sequence
probs[1]

tensor([4.2500e-08, 3.9701e-09, 1.8508e-07, 1.5007e-08, 1.2857e-06, 4.2678e-12,
        6.6631e-08, 3.5985e-09, 2.1752e-11, 4.4544e-04, 9.1054e-11, 1.8323e-10,
        2.2407e-09, 2.2498e-06, 2.1393e-15, 2.9039e-01, 5.7656e-09, 1.1653e-16,
        2.8622e-13, 5.8766e-06, 1.5863e-09, 5.9628e-13, 3.1388e-05, 4.1411e-08,
        5.4792e-10, 8.0928e-14, 7.0913e-01, 9.4507e-14])

### Network evaluation

In [17]:
# iterator over input sequences
it = torch.arange(X_embedded.shape[0])

# extract probabilities for target characters
target_probs = probs[it, Y]

# calculate loss as average negative log likelihood
loss = -torch.log(target_probs).mean()

print(f'Loss before training = {loss}')

Loss before training = 14.686899185180664


# Keep it short and clean without outputs
Above code show detail example of how MLP language model works with one input word.  Since I already went step by step with relevant outputs and example is clear next step is to make this code compact and efficient so it can be used for training and evaluation of language model for whole dataset.

In [18]:
# Build dataset for training
context_length = 3
X, Y = build_dataset(words, context_length)

# Create generator for reproducibility
g = torch.Generator().manual_seed(42)

# Create embedding lookup table with size chars_count
embedding_size = 2
C = torch.randn((chars_count, embedding_size), requires_grad=True, generator=g)

# Embed input sequences
X_embedded = C[X]

# Flatten embedded input sequences, to keep embeddings in one dimension
input_layer_size = X_embedded.shape[1] * X_embedded.shape[2] # context_length * embedding_size
X_embedded_flat = X_embedded.view(-1, input_layer_size)

# Create first neuron layer
hidden_layer_size = 100
W1 = torch.randn((input_layer_size, hidden_layer_size), requires_grad=True, generator=g)
b1 = torch.randn(hidden_layer_size, requires_grad=True, generator=g)

# Create second neuron layer
W2 = torch.randn((hidden_layer_size, chars_count), requires_grad=True, generator=g)
b2 = torch.randn(chars_count, requires_grad=True, generator=g)

# Parameters of the network
params = [C, W1, b1, W2, b2]
print(f'Number of parameters = {sum([p.numel() for p in params])}')

Number of parameters = 3584


# Training loop
Introduce minibatch for training. When training with minibatches we don't fit all ouf our training data at once during each of training loop to calculate gradient and perform parameter update. Instead we split our training data and each epoch we take randomly selected minibatch of data and perform parameter update. This way we don't get exact gradient but we get good approximation of gradient and we can train our model much faster.

In [34]:
epochs = 100
learning_rate = 0.1
mini_batch_size = 500

rand = torch.randint(0, X.shape[0], (mini_batch_size,))

for epoch in range(epochs):
    # Minibatch
    # create tensor with random indices between 0 and X.shape[0] with size mini_batch_size
    ix = torch.randint(0, X.shape[0], (mini_batch_size,))
    
    # Forward pass
    h1 = torch.tanh(X_embedded_flat[ix] @ W1 + b1)
    logits = h1 @ W2 + b2
    loss = F.cross_entropy(logits, Y[ix])
    
    # Print loss
    if epoch % 10 == 0:
        print(f'Epoch {epoch}, loss = {loss}')

    # Backward pass
    loss.backward(retain_graph=True)

    # Update parameters
    for p in params:
        p.data -= learning_rate * p.grad
        p.grad.data.zero_()
        
print(f'Loss after training {epochs} epochs= {loss}')

Epoch 0, loss = 2.78900408744812
Epoch 10, loss = 2.954326868057251
Epoch 20, loss = 2.8300960063934326
Epoch 30, loss = 2.8052523136138916
Epoch 40, loss = 2.7897753715515137
Epoch 50, loss = 2.892972946166992
Epoch 60, loss = 2.7069091796875
Epoch 70, loss = 2.7258033752441406
Epoch 80, loss = 2.7896978855133057
Epoch 90, loss = 2.74900484085083
Loss after training 100 epochs= 2.8442366123199463


## Disclaimer why to use cross entropy vs manual average negative loss likelihood calculation

Calculate mean negative log likelihood based on softmax made of logits
using torch.nn.functional.cross_entropy() which is give same result as:
```python
counts = logits.exp() # this may cause trobles if logits are too big we will get nan, since exp for big numbers is inf
probs = counts / counts.sum(dim=1, keepdim=True)
loss = -torch.log(probs[range(len(Y)), Y]).mean()
```
- but much meory efficient because we do not create intermediate tensors
- and it is safe in case of possible big logits because internally it ofsets them by max logit value
- and much faster and... also makes backpropagation easier :)

# Sample from model

In [20]:
for _ in range(10):
    out = []
    
    context = [stoi[start_token]] * 3
    while True:
        embedding = C[torch.tensor([context])]
        # we always consider only one sequence at a time, so we can set second dimension to -1 and pytorch will figure out the rest
        embedding_flat = embedding.view(1, -1)
        h1 = torch.tanh(embedding_flat @ W1 + b1)
        logits = h1 @ W2 + b2
        probs = F.softmax(logits, dim=1)
        
        # sample next character
        ix = torch.multinomial(probs, num_samples=1, replacement=True).item()
        context = context[1:] + [ix]
        if ix == stoi[end_token]:
            break
        out.append(itos[ix])

    print(''.join(out))

iat<zyaaz
maa
ilymellc
iaai
aai
symir
raz
ryoat<zyaaf
yaatzj
azeaaq
